### ISSUE TITLE
RadioButtonGroup requires label - Actions requires no label

### ISSUE THREAD

**Issue by oakgary** [speee/jsx-slack#111]
When trying to use the RadioButtonGroup Component inside the Actions Component, it suggest that the label on the RadioButtonGroup Component is required. But the Actions Component does not work, when the label is set.

**Comment by yhatt** [comment]
`label` prop for interactive components is required only inside `<Modal>` because it's for the shortcut to [`<Input>` block](https://github.com/speee/jsx-slack/blob/master/docs/layout-blocks.md#input). It cannot define inside `<Actions>`.

Are you talking about the suggestion within your editor such as IntelliSense? `label` should be already suggested as an *optional* property. It shows by trailing `?` like below:

![label](https://user-images.githubusercontent.com/3993388/74265603-2e6a7680-4d46-11ea-9022-172e169739f8.png)

JSX (JavaScript/TypeScript) cannot switch the property suggestion depending on the context of the parent component. Thus, there is no way to hide `label` property suggestion inside `<Actions>` block, and always show all properties that might be taken.

**Comment by oakgary** [comment]
Example:
```
<Modal title="x" close="x" submit="x" callbackId="x">
  <Actions>
    <RadioButtonGroup actionId="x" value="select" required>
      <RadioButton value="x1">
        x
      </RadioButton>
      <RadioButton value="x2">
        x
      </RadioButton>
    </RadioButtonGroup>
  </Actions>
</Modal>
```

The above gives following IntelliSense warning:
```
Type '{ children: Element[]; actionId: string; value: string; required: true; }' is not assignable to type 'Props<(RadioButtonGroupPropsBase & { hint?: undefined; title?: undefined; label?: undefined; required?: undefined; blockId?: undefined; id?: undefined; }) | (RadioButtonGroupPropsBase & InputCommonProps & {})>'.
  Type '{ children: Element[]; actionId: string; value: string; required: true; }' is not assignable to type '{ children?: unknown; } & RadioButtonGroupPropsBase & InputCommonProps & {}'.
    Property 'label' is missing in type '{ children: Element[]; actionId: string; value: string; required: true; }' but required in type 'InputCommonProps'.ts(2322)
```

But adding the label throws an actual error.

**Comment by yhatt** [comment]
It's an expected error. `required` prop is the shortcut into [`<Input>` layout block](https://github.com/speee/jsx-slack/blob/master/docs/layout-blocks.md#input) as same as `label` prop, and `<Actions>` layout block cannot include `<Input>` layout block. TypeScript throws an compile error when you are using component with wrong way.

Remove `required` prop, or move `<RadioButtonGroup>` into the direct children of `<Modal>`.

**Comment by oakgary** [comment]
Removing the required prob worked. Thank you. :)

Moving it out of the Actions Component would not be the same. When it is not inside the Action Component we do not get live requests when the selection changes.

**Comment by yhatt** [comment]
Slack allows both way so use either one depending on your app needs.

Close issue due to resolved.
