### ISSUE TITLE
Interpolation escaping forbids mrkdwn formatted links

### ISSUE THREAD

**Issue by asermax** [speee/jsx-slack#160]
I'm currently working on a project where most of the strings for the messages we send are stored on a CMS. One of the things we wanted to do is to allow the content writter to be able to insert links within the messages; we thought that using slacks'  `markdwn` would be the way to go, but when trying to interpolate a CMS text with a link on it, the `<` and `>` symbols get escaped into their respective html entities, which causes the final message to not be what's expected.

For example:
```jsx
const textWithLink = '<https://example.com|Click here> to read more about the topic!';
const message = (
  <Section>
    {textWithLink}
  <Section>
);
```

will output something like:
```js
{
  ...
  text: {
    type: 'mrkdwn',
    text: '&gt;https://example.com|Click here&lt; to read more about the topic!',
    verbatim: true,
  }
}
```
which will cause the text to be rendered as-is instead of the intended result of having the "Click here" text pointing to the link.

Looking through the code, this seems to be part of the `escapeEntity` logic of the `mrkdwn` module and I couldn't find any way to skip that.
Is this behaviour intentional? Is there any way to mark my string as safe so it doesn't get escaped?

In any case, big congratz in the library; my team and I have been using it and we're really enjoying it!

**Comment by yhatt** [comment]
First, thanks for enjoying our lib! 😄 And yes, escaping into `lt;` and `gt;` is intentional behavior since #45.

Slack mrkdwn has provided a way to escape the link syntax safely, so jsx-slack will escape the text contents into supported HTML entities automatically. This behavior is safe by default as same as the case of using `<` and `>` in React JSX contents. You always have to use `<a>` tag for rendering links in JSX.

JSX has no way to know whether the string is defined in the interpolation or not, so I suppose disabling this encode in only interpolation is difficult.

If you want to use raw mrkdwn, jsx-slack v2 has an easy way to skip this mrkdwn conversion: Define custom component to return JSON inherited from `<Mrkdwn>`, with assigning raw mrkdwn.

```jsx
const RawMrkdwn = (props) => {
  // Generate mrkdwn text composition object (skip unnecessary HTML parsing by assigning children to null)
  const mrkdwn = <Mrkdwn {...props} children={null} />;

  // Define the passed raw mrkdwn as text
  mrkdwn.text = props.children;

  return mrkdwn;
};

const textWithLink = '<https://example.com|Click here> to read more about the topic!';
const message = (
  <Section>
    <RawMrkdwn>{textWithLink}</RawMrkdwn>
  </Section>
);
```

```json
{
  "type": "section",
  "text": {
    "type": "mrkdwn",
    "text": "<https://example.com|Click here> to read more about the topic!"
  }
}
```

**Comment by asermax** [comment]
Alright, it's a shame that it doesn't work out of the box, but it's understandable given the issues it introduces.
We'll be using the workaround you mentioned, thanks a lot!

**Comment by yhatt** [comment]
@asermax Now I made an idea of `<Mrkdwn raw>` based on this: #161. We might work on the out-of-the-box support.
