### ISSUE TITLE
Using map inside of a fragment returns incorrect block structure

### ISSUE THREAD

**Issue by asermax** [speee/jsx-slack#167]
Hey there again!
I ran into an issue when trying to use a fragment to contain multiple blocks, including some generated by a call to an array's `map`.
For example, in this case:
```jsx
<>
  <Section>Test</Section>
  {[1,2,3].map((number) => (
    <Section>{number}</Section>
  ))}
</>
```
would return
```javascript
[
  { type: 'section', text: {...} },
  [
    { type: 'section', text: {...} },
    { type: 'section', text: {...} },
    { type: 'section', text: {...} },
  ],
]
```
while I would expect this instead
```javascript
[
  { type: 'section', text: {...} },
  { type: 'section', text: {...} },
  { type: 'section', text: {...} },
  { type: 'section', text: {...} },
]
```
Using `Blocks` instead of a fragment seems to do the right thing and flatten the array out.

Is this is a known behaviour? Am I doing something wrong?

**Comment by yhatt** [comment]
Yep, it's expected behavior. Actually, _a similar internal structure will output also in React_.

```jsx
// React example
import React from 'react'

const jsx = (
  <>
    <section>Test</section>
    {[1,2,3].map((number) => (
      <section>{number}</section>
    ))}
  </>
)

console.log(jsx.props.children)
// [
//   { type: 'section', props: {...}, ... },
//   [
//     { type: 'section', props: {...}, ... },
//     { type: 'section', props: {...}, ... },
//     { type: 'section', props: {...}, ... },
//   ],
// ]
```

In React component, typically should make flatten through `React.Children.toArray()`. This is the only correct way to handle the opaque data structure of React's children.
https://reactjs.org/docs/react-api.html#reactchildrentoarray

And jsx-slack v2 has also provided `JSXSlack.Children.toArray()` for same purpose. The built-in component `<Blocks>` will spread out nesting arrays by using this API.

In jsx-slack, try wrapping in `JSXSlack.Children.toArray()` if you want to treat the outputted children as a single-dimensional array.

```jsx
JSXSlack.Children.toArray(
  <>
    <Section>Test</Section>
    {[1,2,3].map((number) => (
      <Section>{number}</Section>
    ))}
  </>
)
```

**Comment by asermax** [comment]
Oh alright, so in theory whatever container I use for this component (e.g. if I use it within a `Blocks` or `Home` component) will take care of flattening it out, together with any other children there.
Thanks for the quick answer! I'm learning quite a bit more about `jsx` by using this lib than with using React :stuck_out_tongue:
