### ISSUE TITLE
whitespace formatting bug

### ISSUE THREAD

**Issue by oakgary** [speee/jsx-slack#186]
## With whitespace after colon:
```
<Blocks>
  <Context>
    <b>Test: </b> Hi
    <br></br>
    <b>Test: </b> Hello
  </Context>
</Blocks>
```
-->
![image](https://user-images.githubusercontent.com/13177748/89044298-0bf70480-d34a-11ea-8d13-574ee9faca0b.png)

## Without whitespace after colon:
```
<Blocks>
  <Context>
    <b>Test:</b> Hi
    <br></br>
    <b>Test:</b> Hello
  </Context>
</Blocks>
```
-->
![image](https://user-images.githubusercontent.com/13177748/89044357-229d5b80-d34a-11ea-9509-4d7944d08728.png)

**Comment by yhatt** [comment]
It's not a bug of jsx-slack.

An outputted mrkdwn is just respecting given JSX, mrkdwn, and HTML rendering rule (trimming whitespaces around text node). Thus, `<b>Test: </b>` (with space after colon) is exactly surrounded including space by `*`, and a leading space of <code>&nbsp;Hi</code> is removed.

[![](https://user-images.githubusercontent.com/3993388/89061075-08419d00-d39f-11ea-8606-a63cf6edb5b7.png)](https://jsfiddle.net/o5jgu01h/)


An important fact is that *Slack recognizes markup only when surrounding words correctly*. It's the developer's responsibility to deal with incorrect rendering because jsx-slack hates the implicit change of the text content.

You can try `JSXSlack.exactMode(true)` for getting correct rendering if necessary.
https://github.com/speee/jsx-slack/blob/master/docs/about-escape-and-exact-mode.md#exact-mode

**Comment by oakgary** [comment]
Ok 👍
Thank you for your fast response.
