### ISSUE TITLE
Spaces being trimmed in some circumstances

### ISSUE THREAD

**Issue by asermax** [speee/jsx-slack#210]
I just stumbled with a bug while upgrading to the latest version of the library in which, in some cases, spaces are being trimmed from strings. In particular, this seems to happen when there's a list of `a` tags with some text in between them within a fragment.

For example, the following JSX
```jsx
const SomeComponent = () => (
  <>
    <a href="@a" />
    {', '}
    <a href="@b" />
    {', '}
    <a href="@c" />
  </>
);
```
Would ouput `<@a>, <@b>,<@c>` instead of `<@a>, <@b>, <@c>` (note the space after the last comma). Strangely, the trimming only seems to happen on the text that's one before last, doesn't matter how many elements there are within the fragment. It also seems to be trimming the spaces before and after the text (for example `' and '` would be rendered as `and` without spaces).

I tried going through the code to find where the issue could be steaming from but couldn't find anything that catches my eye except some escaping code that I couldn't quite follow.
Let me know if there's anything else I can provide to further debug this issue!

**Comment by yhatt** [comment]
Trimming spaces itself is intentional behavior to reproduce the output of HTML strictly as mentioned in #186.

If passed an invalid Slack ID such as `@a` into href attribute of a tag, jsx-slack will fallback to regular hyperlink `<a href="@a"></a>`. In this case, a tags are containing empty string so we should collapse beginning and trailing spaces by HTML specification.

[<img width="660" src="https://user-images.githubusercontent.com/3993388/102678426-c26d6000-41eb-11eb-9a38-cadb9629fa51.png">](https://jsfiddle.net/gc3rqm7x/)

Look out no beginning and trailing spaces inside of the text in the right pane.

jsx-slack has already considered unexpected trimming when you've passed a valid user ID like `@UXXXXXXXXXX`, by replacing the content into placeholder. You have to pass a valid ID if you want to get the result of strict rendering.

https://github.com/speee/jsx-slack/blob/d2bb221d584f64ddaaf7fd674e4385575f0e9d07/src/mrkdwn/jsx.ts#L80-L82

**Comment by asermax** [comment]
Oh alright, I was seing this error on a unit test and it seems we were using malformed user ids which was causing this issue to pop up. I just replaced them with actual ids and that fixed the issue.
Thanks for the feedback on this!
