### ISSUE TITLE
Section should not allow text longer than 3000 characters

### ISSUE THREAD

**Issue by caedmon** [speee/jsx-slack#81]

**Comment by yhatt** [comment]
Welcome pull request for the finale of [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

**Comment by shakti97** [comment]
are you talking about the text in the section type?

**Comment by caedmon** [comment]
@shakti97 yes.  Currently it appears to allow any or no text, but from the block kit doc, the text field is required and has a length limit of 3000.

**Comment by anusha5695** [comment]
@caedmon : I would like to pick this

**Comment by caedmon** [comment]
Looks like the text field is actually optional if fields is used, but if present must not be empty.
And if fields is used, there must be at least one valid text object in the fields array.

**Comment by batraman** [comment]
Can I take this up?

**Approach**
1. Utilize a second `opts` parameter in `plainText` and `mrkdwn` methods in `src/block-kit/composition/utils.ts` to take in a maxLength property
2. Run the `text` key with a length checker helper function that throws if maxLength is over the specified limit
3. Pass the maxLength parameter in Section (3000 characters) and Button (75 characters). 
4. Add tests which throw in these two cases. 

I've checked from the Block Kit Builder that the error is the same as mentioned in the documentation in these two cases.

**Comment by yhatt** [comment]
We're always welcome to pull request.

I myself would not work on this because Slack will have already throw error on API side, but it should have worth for someone.

**Comment by yhatt** [comment]
We have already been ready to receive pull request from community, but this issue is too survived long with no pull requests in spite of a lot of declarations for contribution. I suppose this issue has to reconsider if we really should leave this in the issue tracker.

IMO, many users (included us) think that app-side validation does not need because Slack have already validated the output blocks while calling API.

We would close this in a week if received no other actions about this from user.
